// Auto-generated by setupStripe.js
export const STRIPE_PRICES = {
  "starter": {
    "monthly": {
      "priceId": "price_1SjeK2BXiYadZ8OVxr2EsCIG",
      "url": "https://buy.stripe.com/test_aFa00ibu3dQj0aIfZi1VK00"
    },
    "annual": {
      "priceId": "price_1SjeK2BXiYadZ8OVCHWIP4tW",
      "url": "https://buy.stripe.com/test_bJe6oGdCbfYrcXu4gA1VK01"
    }
  },
  "pro": {
    "monthly": {
      "priceId": "price_1SjeK3BXiYadZ8OVkb3wyHT3",
      "url": "https://buy.stripe.com/test_6oU6oG41B4fJ5v29AU1VK02"
    },
    "annual": {
      "priceId": "price_1SjeK4BXiYadZ8OVZ22TgrdS",
      "url": "https://buy.stripe.com/test_cNicN4dCb8vZf5C7sM1VK03"
    }
  },
  "signature": {
    "monthly": {
      "priceId": "price_1SjeK5BXiYadZ8OVbuXkgj7R",
      "url": "https://buy.stripe.com/test_00weVc0PpdQjaPmeVe1VK04"
    },
    "annual": {
      "priceId": "price_1SjeK6BXiYadZ8OV9PrB9xYB",
      "url": "https://buy.stripe.com/test_8x2aEW7dNdQjg9G6oI1VK05"
    }
  },
  "empire": {
    "monthly": {
      "priceId": "price_1SjeK7BXiYadZ8OVPB3qAX67",
      "url": "https://buy.stripe.com/test_fZueVcdCb9A30aI3cw1VK06"
    },
    "annual": {
      "priceId": "price_1SjeK8BXiYadZ8OV96K5vcKN",
      "url": "https://buy.stripe.com/test_aFacN40Pp9A3aPmcN61VK07"
    }
  }
} as const;

export type PlanId = keyof typeof STRIPE_PRICES;
export type BillingCycle = 'monthly' | 'annual';
