// Auto-generated by setupStripe.js
export const STRIPE_PRICES = {
  "starter": {
    "monthly": {
      "priceId": "price_1Sk65GBXiYadZ8OVDiYnzozM",
      "url": "https://buy.stripe.com/test_fZucN4bu3fYr4qYaEY1VK08"
    },
    "annual": {
      "priceId": "price_1Sk65GBXiYadZ8OVOUODJRRb",
      "url": "https://buy.stripe.com/test_28E7sK1Tt9A36z65kE1VK09"
    }
  },
  "pro": {
    "monthly": {
      "priceId": "price_1Sk65IBXiYadZ8OVwrIIMP04",
      "url": "https://buy.stripe.com/test_4gMdR869J7rVe1ybJ21VK0a"
    },
    "annual": {
      "priceId": "price_1Sk65IBXiYadZ8OVC8L3Wrxv",
      "url": "https://buy.stripe.com/test_4gMaEW41Bh2vcXu3cw1VK0b"
    }
  },
  "signature": {
    "monthly": {
      "priceId": "price_1Sk65KBXiYadZ8OVCunAw8Yc",
      "url": "https://buy.stripe.com/test_aFaeVc2Xx3bF6z64gA1VK0c"
    },
    "annual": {
      "priceId": "price_1Sk65KBXiYadZ8OVrDL5rPvU",
      "url": "https://buy.stripe.com/test_14A3cueGf5jNaPm3cw1VK0d"
    }
  },
  "empire": {
    "monthly": {
      "priceId": "price_1Sk65LBXiYadZ8OVjdEcb06f",
      "url": "https://buy.stripe.com/test_aFa00i9lVbIbg9G4gA1VK0e"
    },
    "annual": {
      "priceId": "price_1Sk65MBXiYadZ8OVTWPuKJ7U",
      "url": "https://buy.stripe.com/test_8x2cN41TtdQje1yaEY1VK0f"
    }
  }
} as const;

export type PlanId = keyof typeof STRIPE_PRICES;
export type BillingCycle = 'monthly' | 'annual';
