// Utility to generate a daily quote based on date specific logic
// Supports special holidays and a rotating list of 365 standard days.

interface QuoteAsset {
  text: string;
  author: string;
  image: string;
}

// Collection of High-Quality Backgrounds
const backgrounds = [
  "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?q=80&w=2070&auto=format&fit=crop", // 0
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop", // 1
  "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop", // 2
  "https://images.unsplash.com/photo-1490750967868-bcdf92dd2184?q=80&w=2070&auto=format&fit=crop", // 3
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2070&auto=format&fit=crop", // 4
  "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop", // 5
  "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=2069&auto=format&fit=crop", // 6
  "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=2070&auto=format&fit=crop"  // 7
];

// 1. SPECIAL DATES (MM-DD)
const specialDates: Record<string, { text: string; author: string; image: string }> = {
  '01-01': { text: "Ogni nuovo inizio proviene dalla fine di qualche altro inizio.", author: "Seneca", image: backgrounds[0] },
  '12-25': { text: "Non è quanto diamo, ma quanto amore mettiamo nel dare.", author: "Natale", image: backgrounds[7] },
  '12-31': { text: "Scrivi sul tuo cuore che ogni giorno è il giorno più bello dell'anno.", author: "Fine Anno", image: backgrounds[7] }
};

// 2. GENERAL POOL (365 Quotes)
const genericQuotes = [
  { text: "Your heart is the size of an ocean. Go find yourself in its hidden depths.", author: "Rumi", img: backgrounds[0] },
  { text: "The Bay of Bengal is hit frequently by cyclones. The months of November and May, in particular, are dangerous in this regard.", author: "Abdul Kalam", img: backgrounds[1] },
  { text: "Thinking is the capital, Enterprise is the way, Hard Work is the solution.", author: "Abdul Kalam", img: backgrounds[2] },
  { text: "If You Can'T Make It Good, At Least Make It Look Good.", author: "Bill Gates", img: backgrounds[3] },
  { text: "Heart be brave. If you cannot be brave, just go. Love's glory is not a small thing.", author: "Rumi", img: backgrounds[4] },
  { text: "It is bad for a young man to sin; but it is worse for an old man to sin.", author: "Abu Bakr (R.A)", img: backgrounds[5] },
  { text: "If You Are Out To Describe The Truth, Leave Elegance To The Tailor.", author: "Albert Einstein", img: backgrounds[6] },
  { text: "O man you are busy working for the world, and the world is busy trying to turn you out.", author: "Abu Bakr (R.A)", img: backgrounds[7] },
  { text: "While children are struggling to be unique, the world around them is trying all means to make them look like everybody else.", author: "Abdul Kalam", img: backgrounds[0] },
  { text: "These Capitalists Generally Act Harmoniously And In Concert, To Fleece The People.", author: "Abraham Lincoln", img: backgrounds[1] },
  { text: "I Don'T Believe In Failure. It Is Not Failure If You Enjoyed The Process.", author: "Oprah Winfrey", img: backgrounds[2] },
  { text: "Do not get elated at any victory, for all such victory is subject to the will of God.", author: "Abu Bakr (R.A)", img: backgrounds[3] },
  { text: "Wear gratitude like a cloak and it will feed every corner of your life.", author: "Rumi", img: backgrounds[4] },
  { text: "If you even dream of beating me you'd better wake up and apologize.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "I Will Praise Any Man That Will Praise Me.", author: "William Shakespeare", img: backgrounds[6] },
  { text: "One Of The Greatest Diseases Is To Be Nobody To Anybody.", author: "Mother Teresa", img: backgrounds[7] },
  { text: "I'm so fast that last night I turned off the light switch in my hotel room and was in bed before the room was dark.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "People Must Learn To Hate And If They Can Learn To Hate, They Can Be Taught To Love.", author: "Nelson Mandela", img: backgrounds[1] },
  { text: "Everyone has been made for some particular work, and the desire for that work has been put in every heart.", author: "Rumi", img: backgrounds[2] },
  { text: "The less of the World, the freer you live.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[3] },
  { text: "Respond to every call that excites your spirit.", author: "Rumi", img: backgrounds[4] },
  { text: "The Way To Get Started Is To Quit Talking And Begin Doing.", author: "Walt Disney", img: backgrounds[5] },
  { text: "God Doesn'T Require Us To Succeed, He Only Requires That You Try.", author: "Mother Teresa", img: backgrounds[6] },
  { text: "Speak any language, Turkish, Greek, Persian, Arabic, but always speak with love.", author: "Rumi", img: backgrounds[7] },
  { text: "Happiness comes towards those which believe in him.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[0] },
  { text: "Knowledge is of two kinds: that which is absorbed and that which is heard. And that which is heard does not profit if it is not absorbed.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[1] },
  { text: "When I am silent, I have thunder hidden inside.", author: "Rumi", img: backgrounds[2] },
  { text: "Technological Progress Is Like An Axe In The Hands Of A Pathological Criminal.", author: "Albert Einstein", img: backgrounds[3] },
  { text: "No One Would Choose A Friendless Existence On Condition Of Having All The Other Things In The World.", author: "Aristotle", img: backgrounds[4] },
  { text: "Life is a gamble. You can get hurt, but people die in plane crashes, lose their arms and legs in car accidents; people die every day. Same with fighters: some die, some get hurt, some go on. You just don't let yourself believe it will happen to you.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "The End Of Life Is To Be Like God, And The Soul Following God Will Be Like Him.", author: "Socrates", img: backgrounds[6] },
  { text: "Let us sacrifice our today so that our children can have a better tomorrow.", author: "Abdul Kalam", img: backgrounds[7] },
  { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi", img: backgrounds[0] },
  { text: "In every religion there is love, yet love has no religion.", author: "Rumi", img: backgrounds[1] },
  { text: "Everything in the universe is within you. Ask all from yourself.", author: "Rumi", img: backgrounds[2] },
  { text: "I'm not a handsome guy, but I can give my hand to someone who needs help. Beauty is in the heart, not in the face.", author: "Abdul Kalam", img: backgrounds[3] },
  { text: "What Do I Wear In Bed? Why, Chanel No. 5, Of Course.", author: "Marilyn Monroe", img: backgrounds[4] },
  { text: "A Good Head And A Good Heart Are Always A Formidable Combination.", author: "Nelson Mandela", img: backgrounds[5] },
  { text: "The Soul Never Thinks Without A Picture.", author: "Aristotle", img: backgrounds[6] },
  { text: "In your light I learn how to love. In your beauty, how to make poems. You dance inside my chest where no-one sees you, but sometimes I do, and that sight becomes this art.", author: "Rumi", img: backgrounds[7] },
  { text: "Let the beauty we love be what we do. There are hundreds of ways to kneel and kiss the ground.", author: "Rumi", img: backgrounds[0] },
  { text: "If You Like Your Brother And He'S Prospering, You'Ll Be Pleased For Him.", author: "Hamad Bin Isa Al Khalifa", img: backgrounds[1] },
  { text: "Success Is Dependent Upon The Glands - Sweat Glands.", author: "Zig Ziglar", img: backgrounds[2] },
  { text: "Champions are not generated from the championship. Champion is generated from something they have in them, desires, dreams, and visions.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "No matter what is the environment around you, it is always possible to maintain your brand of integrity.", author: "Abdul Kalam", img: backgrounds[4] },
  { text: "Applause Waits On Success.", author: "Benjamin Franklin", img: backgrounds[5] },
  { text: "Just As Courage Imperils Life, Fear Protects It.", author: "Leonardo Da Vinci", img: backgrounds[6] },
  { text: "It'S Better To Be A Lion For A Day Than A Sheep All Your Life.", author: "Elizabeth Kenny", img: backgrounds[7] },
  { text: "The Devil'S Voice Is Sweet To Hear.", author: "Stephen King", img: backgrounds[0] },
  { text: "Sometimes the people with the worst past, create the best future.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[1] },
  { text: "Every day, nay every moment, try to do some good deed.", author: "Abu Bakr (R.A)", img: backgrounds[2] },
  { text: "No Matter What People Tell You, Words And Ideas Can Change The World.", author: "Robin Williams", img: backgrounds[3] },
  { text: "Champions have to have the skill and the will. But the will must be stronger than the skill.", author: "Muhammad Ali", img: backgrounds[4] },
  { text: "Men Occasionally Stumble Over The Truth, But Most Of Them Pick Themselves Up And Hurry Off As If Nothing Had Happened.", author: "Winston Churchill", img: backgrounds[5] },
  { text: "Goodbyes are only for those who love with their eyes. Because for those who love with heart and soul there is no such thing as separation.", author: "Rumi", img: backgrounds[6] },
  { text: "The best revenge is to improve yourself.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "God gave me this illness to remind me that I'm not Number One; He is.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "Success Is A Personal Standard, Reaching For The Highest That Is In Us, Becoming All That We Can Be.", author: "Zig Ziglar", img: backgrounds[1] },
  { text: "When You Have Really Exhausted An Experience You Always Reverence And Love It.", author: "Albert Camus", img: backgrounds[2] },
  { text: "Now you see me, now you don't. George thinks he will, but I know he won't!", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "Elegance Does Not Consist In Putting On A New Dress.", author: "Coco Chanel", img: backgrounds[4] },
  { text: "It Is Always Consoling To Think Of Suicide: In That Way One Gets Through Many A Bad Night.", author: "Friedrich Nietzsche", img: backgrounds[5] },
  { text: "Eating Words Has Never Given Me Indigestion.", author: "Winston Churchill", img: backgrounds[6] },
  { text: "India has to be transformed into a developed nation, a prosperous nation and a healthy nation, with a value system.", author: "Abdul Kalam", img: backgrounds[7] },
  { text: "It's not bragging if you can back it up.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "I Wish People Would Love Everybody Else The Way They Love Me. It Would Be A Better World.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "Why do I want my wife to show off her panties when the wind blows? Horses show their behinds, and cows and mules, not humans.", author: "Muhammad Ali", img: backgrounds[2] },
  { text: "Words Are Only Painted Fire; A Look Is The Fire Itself.", author: "Mark Twain", img: backgrounds[3] },
  { text: "Words, Without Power, Is Mere Philosophy.", author: "Muhammad Iqbal", img: backgrounds[4] },
  { text: "The cure for pain is in the pain.", author: "Rumi", img: backgrounds[5] },
  { text: "Whatever happens, just keep smiling and lose yourself in Love.", author: "Rumi", img: backgrounds[6] },
  { text: "Do The Right Thing. It Will Gratify Some People And Astonish The Rest.", author: "Mark Twain", img: backgrounds[7] },
  { text: "Only the soul knows what love is.", author: "Rumi", img: backgrounds[0] },
  { text: "Earning of livelihood by following some profession is better than living on charity.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[1] },
  { text: "Burdens are the foundations of ease and bitter things the forerunners of pleasure.", author: "Rumi", img: backgrounds[2] },
  { text: "Too Many Have Dispensed With Generosity In Order To Practice Charity.", author: "Albert Camus", img: backgrounds[3] },
  { text: "Even the greatest was once a beginner. Don't be afraid to take that first step.", author: "Muhammad Ali", img: backgrounds[4] },
  { text: "No Great Intellectual Thing Was Ever Done By Great Effort.", author: "Theodore Roosevelt", img: backgrounds[5] },
  { text: "To fight against one's desires is the greatest of all fights.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[6] },
  { text: "Innovation Distinguishes Between A Leader And A Follower.", author: "Steve Jobs", img: backgrounds[7] },
  { text: "We Enjoy The Process Far More Than The Proceeds.", author: "Warren Buffett", img: backgrounds[0] },
  { text: "When I Started Counting My Blessings, My Whole Life Turned Around.", author: "Willie Nelson", img: backgrounds[1] },
  { text: "This being human is a guest house. Every morning a new arrival. Welcome and entertain them all!", author: "Rumi", img: backgrounds[2] },
  { text: "All My Life I'Ve Looked At Words As Though I Were Seeing Them For The First Time.", author: "Ernest Hemingway", img: backgrounds[3] },
  { text: "Waiting Is Painful. Forgetting Is Painful. But Not Knowing Which To Do Is The Worse Kind Of Suffering.", author: "Paulo Coelho", img: backgrounds[4] },
  { text: "Never Allow Someone To Be Your Priority While Allowing Yourself To Be Their Option.", author: "Mark Twain", img: backgrounds[5] },
  { text: "To Jaw-Jaw Is Always Better Than To War-War.", author: "Winston Churchill", img: backgrounds[6] },
  { text: "That'S The Real Trouble With The World, Too Many People Grow Up", author: "Walt Disney", img: backgrounds[7] },
  { text: "It Is Easier To Stay Out Than Get Out.", author: "Mark Twain", img: backgrounds[0] },
  { text: "The worst man is the one who sees himself as the best.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "The World Breaks Everyone, And Afterward, Some Are Strong At The Broken Places.", author: "Ernest Hemingway", img: backgrounds[2] },
  { text: "Rule No.1: Never Lose Money. Rule No.2: Never Forget Rule No.1.", author: "Warren Buffett", img: backgrounds[3] },
  { text: "Convergence of our views on global trade issues under the WTO and our common resolve to combat terrorism provide a valuable base for mutual understanding.", author: "Abdul Kalam", img: backgrounds[4] },
  { text: "Whenever You Find Yourself On The Side Of The Majority, It Is Time To Pause And Reflect.", author: "Mark Twain", img: backgrounds[5] },
  { text: "Whatever Is Done For Love Always Occurs Beyond Good And Evil.", author: "Friedrich Nietzsche", img: backgrounds[6] },
  { text: "Things Should Be Made As Simple As Possible, But Not Any Simpler.", author: "Albert Einstein", img: backgrounds[7] },
  { text: "Stop acting so small. You are the universe in ecstatic motion.", author: "Rumi", img: backgrounds[0] },
  { text: "All Truth Is Simple... Is That Not Doubly A Lie?", author: "Friedrich Nietzsche", img: backgrounds[1] },
  { text: "Money Is Only A Tool. It Will Take You Wherever You Wish, But It Will Not Replace You As The Driver.", author: "Ayn Rand", img: backgrounds[2] },
  { text: "The fight is won or lost far away from witnesses - behind the lines, in the gym, and out there on the road, long before I dance under those lights.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "He who avoids complaint invites happiness.", author: "Abu Bakr (R.A)", img: backgrounds[4] },
  { text: "We are the mirror - As well as the face in it.", author: "Rumi", img: backgrounds[5] },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", img: backgrounds[6] },
  { text: "For 2,500 years, India has never invaded anybody.", author: "Abdul Kalam", img: backgrounds[7] },
  { text: "If Past History Was All There Was To The Game, The Richest People Would Be Librarians.", author: "Warren Buffett", img: backgrounds[0] },
  { text: "Your souls are precious and can only be equal to the price of Paradise, therefore sell them only at that price.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[1] },
  { text: "A Wise Man Can Learn More From A Foolish Question Than A Fool Can Learn From A Wise Answer.", author: "Bruce Lee", img: backgrounds[2] },
  { text: "If Allah wants for a people ill, he gives them debates and takes away from them actions.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[3] },
  { text: "He who builds a masjid in the way of Allah, God will build a house for him in the paradise.", author: "Abu Bakr (R.A)", img: backgrounds[4] },
  { text: "Love Is Blind; Friendship Closes Its Eyes.", author: "Friedrich Nietzsche", img: backgrounds[5] },
  { text: "Don'T Go Around Saying The World Owes You A Living. The World Owes You Nothing. It Was Here First.", author: "Mark Twain", img: backgrounds[6] },
  { text: "An alert and learned man will take advice from any event.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "I don't count my sit-ups. I only start counting when it starts hurting. When I feel pain, that's when I start counting, because that's when it really counts.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "The wound is the place where the Light enters you.", author: "Rumi", img: backgrounds[1] },
  { text: "Luxury is an obstacle, and so is the fatness of the body.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[2] },
  { text: "Come, come, whoever you are. Wanderer, worshiper, lover of leaving. It doesn't matter. Ours is not a caravan of despair. come, even if you have broken your vows a thousand times. Come, yet again, come, come.", author: "Rumi", img: backgrounds[3] },
  { text: "The Golden Age Is Before Us, Not Behind Us.", author: "William Shakespeare", img: backgrounds[4] },
  { text: "Fiction Is The Truth Inside The Lie.", author: "Stephen King", img: backgrounds[5] },
  { text: "Believe You Can And You'Re Halfway There.", author: "Theodore Roosevelt", img: backgrounds[6] },
  { text: "All The Great Things Are Simple, And Many Can Be Expressed In A Single Word: Freedom, Justice, Honor, Duty, Mercy, Hope.", author: "Winston Churchill", img: backgrounds[7] },
  { text: "Allah's the Arabic term for God. Stand up for God, fight for God, work for God and do the right thing, and go the right way, things will end up in your corner.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "Anger Is Never Without A Reason, But Seldom With A Good One.", author: "Benjamin Franklin", img: backgrounds[1] },
  { text: "Good Actions Are A Guard Against The Blows Of Adversity.", author: "Abu Bakr", img: backgrounds[2] },
  { text: "Use the same measure for selling that you use for purchasing.", author: "Abu Bakr (R.A)", img: backgrounds[3] },
  { text: "The Secret Of Getting Ahead Is Getting Started", author: "Mark Twain", img: backgrounds[4] },
  { text: "I Don'T Know The Key To Success, But The Key To Failure Is Trying To Please Everybody.", author: "Bill Cosby", img: backgrounds[5] },
  { text: "Real Loss Is Only Possible When You Love Something More Than You Love Yourself.", author: "Robin Williams", img: backgrounds[6] },
  { text: "This Is The First Convention Of The Space Age - Where A Candidate Can Promise The Moon And Mean It.", author: "David Brinkley", img: backgrounds[7] },
  { text: "I Don'T Like That Man. I Must Get To Know Him Better.", author: "Abraham Lincoln", img: backgrounds[0] },
  { text: "To Shipbrokers, Coal Was Black Gold.", author: "Roald Dahl", img: backgrounds[1] },
  { text: "History, Despite Its Wrenching Pain, Cannot Be Unlived, But If Faced With Courage, Need Not Be Lived Again.", author: "Maya Angelou", img: backgrounds[2] },
  { text: "Everyone who is taken by death asks for more time, while everyone who still has time makes excuses for procrastination.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[3] },
  { text: "I wonder at a man who loses hope of salvation when the door of repentance is open for him.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[4] },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "Close your eyes, fall in Love, stay there.", author: "Rumi", img: backgrounds[6] },
  { text: "I Guess I Don'T So Much Mind Being Old, As I Mind Being Fat And Old.", author: "Benjamin Franklin", img: backgrounds[7] },
  { text: "It will be a killer, and a chiller, and a thriller, when I get the gorilla in Manila.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "I Dream Of An Africa Which Is In Peace With Itself.", author: "Nelson Mandela", img: backgrounds[1] },
  { text: "The Difference Between A Mountain And A Molehill Is Your Perspective.", author: "Al Neuharth", img: backgrounds[2] },
  { text: "I Am Certainly Not One Of Those Who Need To Be Prodded. In Fact, If Anything, I Am The Prod.", author: "Winston Churchill", img: backgrounds[3] },
  { text: "To the people that have said I'm too small, I'm not fast enough, I don't have what it takes, I'm not strong enough. THANK YOU.", author: "Muhammad Ali", img: backgrounds[4] },
  { text: "There is a King Who is aware of every Mask you put on.", author: "Rumi", img: backgrounds[5] },
  { text: "Be patient; patience is a pillar of faith.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[6] },
  { text: "The Very Ink With Which History Is Written Is Merely Fluid Prejudice.", author: "Mark Twain", img: backgrounds[7] },
  { text: "I was the first one in the gym, and the last one to leave.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "Art Is The Proper Task Of Life.", author: "Friedrich Nietzsche", img: backgrounds[1] },
  { text: "The Roots Of Education Are Bitter, But The Fruit Is Sweet.", author: "Aristotle", img: backgrounds[2] },
  { text: "Run away from greatness and greatness will follow you.", author: "Abu Bakr (R.A)", img: backgrounds[3] },
  { text: "You may learn to imitate a birdcall, but do you experience what the nightingale feels for the rose?", author: "Rumi", img: backgrounds[4] },
  { text: "Bad Men Are Full Of Repentance.", author: "Aristotle", img: backgrounds[5] },
  { text: "Blessed is he whose own faults keep him from seeing the faults of others.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[6] },
  { text: "The most helpless person is the one who is helpless in reforming himself.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "He who fears to weep, should learn to be kind to those who weep.", author: "Abu Bakr (R.A)", img: backgrounds[0] },
  { text: "My wealth is in my knowledge of self, love, and spirituality.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "He who aspires to paradise should learn to deal with people with kindness.", author: "Abu Bakr (R.A)", img: backgrounds[2] },
  { text: "All God's creatures are His family; and he is the most beloved of God who tries to do most good to God's creatures.", author: "Abdul Kalam", img: backgrounds[3] },
  { text: "When I Do Good, I Feel Good. When I Do Bad, I Feel Bad. That'S My Religion.", author: "Abraham Lincoln", img: backgrounds[4] },
  { text: "Women are not equal with men, that's sure. When the woman is in danger she always looks to the man for help. We are superior by nature. The black or white woman needn't worry in life because the world is ruled by the white man.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "If you love someone, you are always joined with them - in joy, in absence, in solitude, in strife.", author: "Rumi", img: backgrounds[6] },
  { text: "I Am A Deeply Religious Nonbeliever - This Is A Somewhat New Kind Of Religion.", author: "Albert Einstein", img: backgrounds[7] },
  { text: "It Is The Supreme Art Of The Teacher To Awaken Joy In Creative Expression And Knowledge.", author: "Albert Einstein", img: backgrounds[0] },
  { text: "The best companion and helper is admirable morals.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[1] },
  { text: "Man Will Do Many Things To Get Himself Loved, He Will Do All Things To Get Himself Envied.", author: "Mark Twain", img: backgrounds[2] },
  { text: "When you seek advice, do not withhold any facts from the person whose advice you seek.", author: "Abu Bakr (R.A)", img: backgrounds[3] },
  { text: "I have never regretted my silence. As for my speech, I have regretted it over and over again.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[4] },
  { text: "Don't read success stories, you will only get a message. Read failure stories, you will get some ideas to get success.", author: "Abdul Kalam", img: backgrounds[5] },
  { text: "I Have Nothing To Offer But Blood, Toil, Tears And Sweat.", author: "Winston Churchill", img: backgrounds[6] },
  { text: "I died as a mineral and became a plant, I died as a plant and rose to animal, I died as an animal and I was Man. Why should I fear? When was I less by dying?", author: "Rumi", img: backgrounds[7] },
  { text: "All Men'S Souls Are Immortal, But The Souls Of The Righteous Are Immortal And Divine.", author: "Socrates", img: backgrounds[0] },
  { text: "Abstinence from sins is better than seeking help afterwards.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[1] },
  { text: "Inside the Great Mystery that is, we don't really own anything. What is this competition we feel then, before we go, one at a time, through the same gate?", author: "Rumi", img: backgrounds[2] },
  { text: "The only lasting beauty is the beauty of the heart.", author: "Rumi", img: backgrounds[3] },
  { text: "Change Your Opinions, Keep To Your Principles; Change Your Leaves, Keep Intact Your Roots.", author: "Victor Hugo", img: backgrounds[4] },
  { text: "Many Marriages Would Be Better If The Husband And The Wife Clearly Understood That They Are On The Same Side.", author: "Zig Ziglar", img: backgrounds[5] },
  { text: "Strong And Bitter Words Indicate A Weak Cause.", author: "Victor Hugo", img: backgrounds[6] },
  { text: "A man who views the world the same at fifty as he did at twenty has wasted thirty years of his life.", author: "Muhammad Ali", img: backgrounds[7] },
  { text: "Give up to grace. The ocean takes care of each wave 'til it gets to shore. You need more help than you know.", author: "Rumi", img: backgrounds[0] },
  { text: "The Superior Man Acts Before He Speaks, And Afterwards Speaks According To His Action.", author: "Confucius", img: backgrounds[1] },
  { text: "We'Re Getting Hurt, But I'M A Long-Term Investor.", author: "Al Waleed Bin Talal", img: backgrounds[2] },
  { text: "Recitation of the Qur'an without contemplation and thought is futile.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[3] },
  { text: "Success is not achieved by winning all the time. Real success comes when we rise after we fall. Some mountains are higher than others. Some roads steeper than the next. There are hardships and setbacks but you cannot let them stop you. Even on the steepest road you must not turn back.", author: "Muhammad Ali", img: backgrounds[4] },
  { text: "A Riot Is The Language Of The Unheard.", author: "Martin Luther King, Jr.", img: backgrounds[5] },
  { text: "The Law Is Reason, Free From Passion.", author: "Aristotle", img: backgrounds[6] },
  { text: "The people who abandon Jihad fall a victim to humility and degradation.", author: "Abu Bakr (R.A)", img: backgrounds[7] },
  { text: "We are all born with a divine fire in us. Our efforts should be to give wings to this fire and fill the world with the glow of its goodness.", author: "Abdul Kalam", img: backgrounds[0] },
  { text: "Woman Was God'S Second Mistake.", author: "Friedrich Nietzsche", img: backgrounds[1] },
  { text: "All black Americans have slave names. They have white names; names that the slave master has given to them.", author: "Muhammad Ali", img: backgrounds[2] },
  { text: "I'm most proud of my family.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "And you? When will you begin that long journey into yourself?", author: "Rumi", img: backgrounds[4] },
  { text: "How many lessons there are and how little they are taken.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[5] },
  { text: "The best way to make your dreams come true is to wake up.", author: "Muhammad Ali", img: backgrounds[6] },
  { text: "What One Writer Can Make In The Solitude Of One Room Is Something No Power Can Easily Destroy.", author: "Salman Rushdie", img: backgrounds[7] },
  { text: "If There Is Something To Pardon In Everything, There Is Also Something To Condemn.", author: "Friedrich Nietzsche", img: backgrounds[0] },
  { text: "At Home I Am A Nice Guy: But I Don'T Want The World To Know. Humble People, I'Ve Found, Don'T Get Very Far.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "No amount of guilt can change the past and no amount of worrying can change the future.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[2] },
  { text: "Not the ones speaking the same language, but the ones sharing the same feeling understand each other.", author: "Rumi", img: backgrounds[3] },
  { text: "It Is Better To Deserve Honors And Not Have Them Than To Have Them And Not Deserve Them.", author: "Mark Twain", img: backgrounds[4] },
  { text: "Success Is A Lousy Teacher. It Seduces Smart People Into Thinking They Can'T Lose.", author: "Bill Gates", img: backgrounds[5] },
  { text: "Cursed is the man who dies, but the evil done by him survives.", author: "Abu Bakr (R.A)", img: backgrounds[6] },
  { text: "The Quality, Not The Longevity, Of One'S Life Is What Is Important.", author: "Martin Luther King, Jr.", img: backgrounds[7] },
  { text: "Age is whatever you think it is. You are as old as you think you are.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "Derivatives Are Financial Weapons Of Mass Destruction.", author: "Warren Buffett", img: backgrounds[1] },
  { text: "Don't you know yet? It is your Light that lights the worlds.", author: "Rumi", img: backgrounds[2] },
  { text: "Hold on to your Salah, because if you lose that, you will lose everything else.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[3] },
  { text: "I am not this hair. I am not this skin. I am the soul that lives within.", author: "Rumi", img: backgrounds[4] },
  { text: "Be Faithful In Small Things Because It Is In Them That Your Strength Lies.", author: "Mother Teresa", img: backgrounds[5] },
  { text: "He who sleeps without offering the night prayer, may he never enjoy a sound sleep.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[6] },
  { text: "I Was Influenced A Lot By Those Around Me - There Was A Lot Of Singing That Went On In The Cotton Fields.", author: "Willie Nelson", img: backgrounds[7] },
  { text: "Greed is permanent slavery.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[0] },
  { text: "Everything That We See Is A Shadow Cast By That Which We Do Not See.", author: "Martin Luther King, Jr.", img: backgrounds[1] },
  { text: "To The Master'S Honor All Must Turn, Each In Its Track, Without A Sound, Forever Tracing Newton'S Ground.", author: "Albert Einstein", img: backgrounds[2] },
  { text: "Women are the field that produces our nation. And if you can't protect your women, you can't protect your nation.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "To Give Victory To The Right, Not Bloody Bullets, But Peaceful Ballots Only, Are Necessary.", author: "Abraham Lincoln", img: backgrounds[4] },
  { text: "The Ache For Home Lives In All Of Us, The Safe Place Where We Can Go As We Are And Not Be Questioned.", author: "Maya Angelou", img: backgrounds[5] },
  { text: "You Were Born To Win, But To Be A Winner, You Must Plan To Win, Prepare To Win, And Expect To Win.", author: "Zig Ziglar", img: backgrounds[6] },
  { text: "Education Is What Remains After One Has Forgotten What One Has Learned In School.", author: "Albert Einstein", img: backgrounds[7] },
  { text: "I'll tell you how I'd like to be remembered: As a black man who won the heavyweight title - Who has humorous and who never looked down on those who looked up to him - A man who stood for freedom, justice and equality - And I wouldn't even mind if folks forgot how pretty I was.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "Tolerance and understanding won't 'trickle down' in our society any more than wealth does.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "It Does Not Do To Dwell On Dreams And Forget To Live.", author: "J. K. Rowling", img: backgrounds[2] },
  { text: "Courtesy costs nothing, but buys everything.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[3] },
  { text: "If patience and gratitude had been she camels, it would have mattered little on which I rode.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[4] },
  { text: "Success Consists Of Going From Failure To Failure Without Loss Of Enthusiasm.", author: "Winston Churchill", img: backgrounds[5] },
  { text: "When you advise any person you should be guided by the fear of God.", author: "Abu Bakr (R.A)", img: backgrounds[6] },
  { text: "A Candle never Loses any of its Light while Lighting up another candle.", author: "Rumi", img: backgrounds[7] },
  { text: "What Can You Do To Promote World Peace? Go Home And Love Your Family.", author: "Mother Teresa", img: backgrounds[0] },
  { text: "Love Is The Only Force Capable Of Transforming An Enemy Into Friend.", author: "Martin Luther King  Jr.", img: backgrounds[1] },
  { text: "Children make you want to start life over.", author: "Muhammad Ali", img: backgrounds[2] },
  { text: "Our Scientific Power Has Outrun Our Spiritual Power. We Have Guided Missiles And Misguided Men.", author: "Martin Luther King, Jr.", img: backgrounds[3] },
  { text: "After Coming Into Contact With A Religious Man I Always Feel I Must Wash My Hands.", author: "Friedrich Nietzsche", img: backgrounds[4] },
  { text: "I Am The Greatest, I Said That Even Before I Knew I Was.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "He who went to the kings to seek favors went away from Allah.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[6] },
  { text: "Oh writer! An Angel watches over all you write. Make your writing meaningful for it will eventually return to you and you will be questioned about what you wrote.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "Speak a new language so that the world will be a new world.", author: "Rumi", img: backgrounds[0] },
  { text: "The sweetness of life lies in dispensing with formalities.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "O Love, O pure deep Love, be here, be now, be all...", author: "Rumi", img: backgrounds[2] },
  { text: "I Never Did A Day'S Work In My Life. It Was All Fun.", author: "Thomas A. Edison", img: backgrounds[3] },
  { text: "We have not invaded anyone. We have not conquered anyone. We have not grabbed their land, their culture, their history and tried to enforce our way of life on them.", author: "Abdul Kalam", img: backgrounds[4] },
  { text: "I have been a seeker and I still am, but I stopped asking the books and the stars. I started listening to the teaching of my Soul.", author: "Rumi", img: backgrounds[5] },
  { text: "Be active! Take on responsibility! Work for the things you believe in. If you do not, you are surrendering your fate to others.", author: "Abdul Kalam", img: backgrounds[6] },
  { text: "Don'T Tell Fish Stories Where The People Know You; But Particularly, Don'T Tell Them Where They Know The Fish.", author: "Mark Twain", img: backgrounds[7] },
  { text: "Developing nations want to become developed nations.", author: "Abdul Kalam", img: backgrounds[0] },
  { text: "We are born of love. Love is our mother.", author: "Rumi", img: backgrounds[1] },
  { text: "I Just Feel Happy To Be In America, Like I Said, It'S The Most Beautiful Country In The World.", author: "Ahmed Ali", img: backgrounds[2] },
  { text: "Do for this life as if you live forever, do for the afterlife as if you will die tomorrow.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[3] },
  { text: "You Know You Are On The Road To Success If You Would Do Your Job, And Not Be Paid For It.", author: "Oprah Winfrey", img: backgrounds[4] },
  { text: "A Compliment Is Something Like A Kiss Through A Veil.", author: "Victor Hugo", img: backgrounds[5] },
  { text: "Last night I had a dream. When I got to Africa, I had one hell of a rumble. I had to beat Tarzan's behind first, for claiming to be King of the Jungle.", author: "Muhammad Ali", img: backgrounds[6] },
  { text: "I Have Found The Paradox, That If You Love Until It Hurts, There Can Be No More Hurt, Only More Love.", author: "Mother Teresa", img: backgrounds[7] },
  { text: "After Climbing A Great Hill, One Only Finds That There Are Many More Hills To Climb.", author: "Nelson Mandela", img: backgrounds[0] },
  { text: "An Explanation Of Cause Is Not A Justification By Reason.", author: "C. S. Lewis", img: backgrounds[1] },
  { text: "His hands can't hit what his eyes can't see.", author: "Muhammad Ali", img: backgrounds[2] },
  { text: "Life Loves The Liver Of It.", author: "Maya Angelou", img: backgrounds[3] },
  { text: "Light up the fire of love inside and blaze the thoughts away.", author: "Rumi", img: backgrounds[4] },
  { text: "Don't sit and wait. Get out there, feel life. Touch the sun, and immerse in the sea.", author: "Rumi", img: backgrounds[5] },
  { text: "There is a way between voice and presence, where information flows. In disciplined silence it opens; with wandering talk it closes.", author: "Rumi", img: backgrounds[6] },
  { text: "Strength Does Not Come From Physical Capacity. It Comes From An Indomitable Will.", author: "Mahatma Gandhi", img: backgrounds[7] },
  { text: "This life is not real. I conquered the world and it did not bring me satisfaction.", author: "Muhammad Ali", img: backgrounds[0] },
  { text: "It'S Fine To Celebrate Success But It Is More Important To Heed The Lessons Of Failure.", author: "Bill Gates", img: backgrounds[1] },
  { text: "Stubbornness destroys good advice.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[2] },
  { text: "My definition of evil is unfriendliness.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "Climbing to the top demands strength, whether it is to the top of Mount Everest or to the top of your career.", author: "Abdul Kalam", img: backgrounds[4] },
  { text: "Pray, And Let God Worry.", author: "Martin Luther", img: backgrounds[5] },
  { text: "Miracles Do Not, In Fact, Break The Laws Of Nature.", author: "C. S. Lewis", img: backgrounds[6] },
  { text: "There is no greater wealth than wisdom, no greater poverty than ignorance; no greater heritage than culture and no greater support than consultation.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "We Are What We Believe We Are.", author: "C. S. Lewis", img: backgrounds[0] },
  { text: "I Feel Much Freer Now That I Am Certain The Pope Is The Antichrist.", author: "Martin Luther", img: backgrounds[1] },
  { text: "Darkness Cannot Drive Out Darkness; Only Light Can Do That. Hate Cannot Drive Out Hate; Only Love Can Do That.", author: "Martin Luther King  Jr.", img: backgrounds[2] },
  { text: "A developed India by 2020, or even earlier, is not a dream. It need not be a mere vision in the minds of many Indians. It is a mission we can all take up - and succeed.", author: "Abdul Kalam", img: backgrounds[3] },
  { text: "As To The Mental Essence, We Find It In Infants Devoid Of Every Mental Form.", author: "Avicenna", img: backgrounds[4] },
  { text: "Let not your love become attachment, nor your hate become destruction.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[5] },
  { text: "He Is Winding The Watch Of His Wit; By And By It Will Strike.", author: "William Shakespeare", img: backgrounds[6] },
  { text: "Don't be sad! Because God sends hope in the most desperate moments. Don't forget, the heaviest rain comes out of the darkest clouds.", author: "Rumi", img: backgrounds[7] },
  { text: "There Cannot Be A God Because If There Were One, I Could Not Believe That I Was Not He.", author: "Friedrich Nietzsche", img: backgrounds[0] },
  { text: "Don't get lost in your pain, know that one day your pain will become your cure.", author: "Rumi", img: backgrounds[1] },
  { text: "Silence gives answers.", author: "Rumi", img: backgrounds[2] },
  { text: "A Man Who Won'T Die For Something Is Not Fit To Live.", author: "Martin Luther King, Jr.", img: backgrounds[3] },
  { text: "Solitude is better than the society of evil persons.", author: "Abu Bakr (R.A)", img: backgrounds[4] },
  { text: "The Only Real Progress Lies In Learning To Be Wrong All Alone.", author: "Albert Camus", img: backgrounds[5] },
  { text: "Drink! For You Know Not Whence You Came Nor Why: Drink! For You Know Not Why You Go, Nor Where.", author: "Omar Khayyam", img: backgrounds[6] },
  { text: "I Shall The Effect Of This Good Lesson Keeps As Watchman To My Heart.", author: "William Shakespeare", img: backgrounds[7] },
  { text: "Vanity prevents improvement.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[0] },
  { text: "Every Day, Nay Every Moment, Try To Do Some Good Deed.", author: "Abu Bakr", img: backgrounds[1] },
  { text: "Money cannot help lifting its head.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[2] },
  { text: "To Think Of Shadows Is A Serious Thing.", author: "Victor Hugo", img: backgrounds[3] },
  { text: "If We Really Want To Love We Must Learn How To Forgive.", author: "Mother Teresa", img: backgrounds[4] },
  { text: "Music Expresses That Which Cannot Be Put Into Words.", author: "Victor Hugo", img: backgrounds[5] },
  { text: "Love Is A Fruit In Season At All Times, And Within Reach Of Every Hand.", author: "Mother Teresa", img: backgrounds[6] },
  { text: "To be able to give away riches is mandatory if you wish to possess them. This is the only way that you will be truly rich.", author: "Muhammad Ali", img: backgrounds[7] },
  { text: "We Continue To Shape Our Personality All Our Life. If We Knew Ourselves Perfectly, We Should Die.", author: "Albert Camus", img: backgrounds[0] },
  { text: "Your longing for ME is my message to you, All your attempts to reach ME, Are in reality MY attempts to reach you.", author: "Rumi", img: backgrounds[1] },
  { text: "If you are greeted then return the greetings more warmly. If you are favored, then repay the obligation manifold; but he who takes the initiative will always excel in merit.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[2] },
  { text: "You have to keep breaking your heart until it opens.", author: "Rumi", img: backgrounds[3] },
  { text: "Prejudice comes from being in the dark; sunlight disinfects it.", author: "Muhammad Ali", img: backgrounds[4] },
  { text: "Never Put Off Till Tomorrow What You Can Do The Day After Tomorrow.", author: "Mark Twain", img: backgrounds[5] },
  { text: "Nothing hurts a good soul and kind heart more than to live amongst people who can't understand it.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[6] },
  { text: "Hope Is The Dream Of A Waking Man.", author: "Aristotle", img: backgrounds[7] },
  { text: "We Make A Living By What We Get, But We Make A Life By What We Give.", author: "Winston Churchill", img: backgrounds[0] },
  { text: "I am so mad with love that mad men say to me - be still!", author: "Rumi", img: backgrounds[1] },
  { text: "If you only say one prayer in a day make it Thank You.", author: "Rumi", img: backgrounds[2] },
  { text: "Life'S Most Persistent And Urgent Question Is, 'What Are You Doing For Others?'", author: "Martin Luther King  Jr.", img: backgrounds[3] },
  { text: "Confidence and hard work is the best medicine to kill the disease called failure. It will make you successful person.", author: "Abdul Kalam", img: backgrounds[4] },
  { text: "The bird is powered by its own life and by its motivation.", author: "Abdul Kalam", img: backgrounds[5] },
  { text: "Allah's Generosity is connected to gratitude, and gratitude is linked to increase in His generosity. The generosity of Allah will not stop increasing unless the gratitude of the servant ceases.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[6] },
  { text: "Bear sorrows and calamities patiently, otherwise you will never be happy.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[7] },
  { text: "One lesson that every nation can learn from China is to focus more on creating village-level enterprises, quality health services and educational facilities.", author: "Abdul Kalam", img: backgrounds[0] },
  { text: "Like Slavery And Apartheid, Poverty Is Not Natural. It Is Man-Made And It Can Be Overcome And Eradicated By The Actions Of Human Beings.", author: "Nelson Mandela", img: backgrounds[1] },
  { text: "Never Do Anything Against Conscience Even If The State Demands It.", author: "Albert Einstein", img: backgrounds[2] },
  { text: "When you feel a peaceful joy, that's when you are near truth.", author: "Rumi", img: backgrounds[3] },
  { text: "I grow silent. Dear soul, you speak.", author: "Rumi", img: backgrounds[4] },
  { text: "All wars signify the failure of conflict resolution mechanisms, and they need post-war rebuilding of faith, trust and confidence.", author: "Abdul Kalam", img: backgrounds[5] },
  { text: "What you're thinking is what you're becoming.", author: "Muhammad Ali", img: backgrounds[6] },
  { text: "I Paint Self-Portraits Because I Am So Often Alone, Because I Am The Person I Know Best.", author: "Frida Kahlo", img: backgrounds[7] },
  { text: "In Music The Passions Enjoy Themselves.", author: "Friedrich Nietzsche", img: backgrounds[0] },
  { text: "That's how you came here, like a star without a name. Move across the night sky with those anonymous lights.", author: "Rumi", img: backgrounds[1] },
  { text: "Your light is more magnificent than sunrise or sunset.", author: "Rumi", img: backgrounds[2] },
  { text: "No One Has Ever Become Poor By Giving.", author: "Anne Frank", img: backgrounds[3] },
  { text: "Whatever pearl you seek, look for the pearl within the pearl!", author: "Rumi", img: backgrounds[4] },
  { text: "India should walk on her own shadow - we must have our own development model.", author: "Abdul Kalam", img: backgrounds[5] },
  { text: "You have escaped the cage. Your wings are stretched out. Now fly.", author: "Rumi", img: backgrounds[6] },
  { text: "Work As If You Were To Live A Hundred Years. Pray As If You Were To Die Tomorrow.", author: "Benjamin Franklin", img: backgrounds[7] },
  { text: "Whenever you are alone, remind yourself that God has sent everyone else away so that there is only you and Him.", author: "Rumi", img: backgrounds[0] },
  { text: "When a man puts me a question, I judge of his intelligence.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[1] },
  { text: "There Has Never Yet Been A Man In Our History Who Led A Life Of Ease Whose Name Is Worth Remembering.", author: "Theodore Roosevelt", img: backgrounds[2] },
  { text: "A teacher should have a creative mind.", author: "Abdul Kalam", img: backgrounds[3] },
  { text: "The criterion of action is that todays work should not be deferred till the following day.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[4] },
  { text: "Friendship is the hardest thing in the world to explain. It's not something you learn in school. But if you haven't learned the meaning of friendship, you really haven't learned anything.", author: "Muhammad Ali", img: backgrounds[5] },
  { text: "The chess master says nothing, other than moving the silent chess piece.", author: "Rumi", img: backgrounds[6] },
  { text: "Reader, Suppose You Were An Idiot. And Suppose You Were A Member Of Congress. But I Repeat Myself.", author: "Mark Twain", img: backgrounds[7] },
  { text: "I Love Sleep. My Life Has The Tendency To Fall Apart When I'M Awake, You Know?", author: "Ernest Hemingway", img: backgrounds[0] },
  { text: "He That Can Have Patience Can Have What He Will.", author: "Benjamin Franklin", img: backgrounds[1] },
  { text: "Champions Keep Playing Until They Get It Right.", author: "Billie Jean King", img: backgrounds[2] },
  { text: "Without Music, Life Would Be A Mistake.", author: "Friedrich Nietzsche", img: backgrounds[3] },
  { text: "The worst of our faults is our interest in other people's faults.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[4] },
  { text: "I Think It'S Nice For Women To Try To Be Sexy For Their Man.", author: "Salma Hayek", img: backgrounds[5] },
  { text: "My impression of the American people can be summarized by a quotation from Benjamin Franklin, Those things that hurt instruct! I realized that people in this part of the world meet their problems head on. They attempt to get out of them rather than suffer them.", author: "Abdul Kalam", img: backgrounds[6] },
  { text: "Boys, You Must Strive To Find Your Own Voice, Because The Longer You Wait To Begin The Less Likely You Are To Find It At All.", author: "Robin Williams", img: backgrounds[7] },
  { text: "Be dignified, honest and truthful.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[0] },
  { text: "Women are not a garment you wear and undress however you like. They are honored and have their rights.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[1] },
  { text: "Love Matches, So Called, Have Illusion For Their Father And Need For Their Mother.", author: "Friedrich Nietzsche", img: backgrounds[2] },
  { text: "A Lot Of People Quit Looking For Work As Soon As They Find A Job.", author: "Zig Ziglar", img: backgrounds[3] },
  { text: "If We Open A Quarrel Between Past And Present, We Shall Find That We Have Lost The Future.", author: "Winston Churchill", img: backgrounds[4] },
  { text: "Even If I Knew That Tomorrow The World Would Go To Pieces, I Would Still Plant My Apple Tree.", author: "Martin Luther", img: backgrounds[5] },
  { text: "One who rushes madly after inordinate desire, runs the risk of encountering destruction and death.", author: "Ali ibn Abi Talib (R.A)", img: backgrounds[6] },
  { text: "Getting Over A Painful Experience Is Much Like Crossing Monkey Bars. You Have To Let Go At Some Point In Order To Move Forward.", author: "C. S. Lewis", img: backgrounds[7] },
  { text: "You Have Enemies? Good. That Means You'Ve Stood Up For Something, Sometime In Your Life.", author: "Winston Churchill", img: backgrounds[0] },
  { text: "It's the repetition of affirmations that leads to belief. And once that belief becomes a deep conviction, things begin to happen.", author: "Muhammad Ali", img: backgrounds[1] },
  { text: "If I Were Not A Physicist, I Would Probably Be A Musician. I Often Think In Music. I Live My Daydreams In Music. I See My Life In Terms Of Music.", author: "Albert Einstein", img: backgrounds[2] },
  { text: "We will be remembered only if we give to our younger generation a prosperous and safe India, resulting out of economic prosperity coupled with civilizational heritage.", author: "Abdul Kalam", img: backgrounds[3] },
  { text: "There is a field beyond all notions of right and wrong. Come, meet me there.", author: "Rumi", img: backgrounds[4] },
  { text: "Even The Darkest Night Will End And The Sun Will Rise.", author: "Victor Hugo", img: backgrounds[5] },
  { text: "Feet, What Do I Need You For When I Have Wings To Fly?", author: "Frida Kahlo", img: backgrounds[6] },
  { text: "Whoever Would Overthrow The Liberty Of A Nation Must Begin By Subduing The Freeness Of Speech.", author: "Benjamin Franklin", img: backgrounds[7] },
  { text: "Spread Love Everywhere You Go. Let No One Ever Come To You Without Leaving Happier.", author: "Mother Teresa", img: backgrounds[0] },
  { text: "One of the very important characteristics of a student is to question. Let the students ask questions.", author: "Abdul Kalam", img: backgrounds[1] },
  { text: "To fight against the infidels is Jihad; but to fight against your evil self is greater Jihad.", author: "Abu Bakr (R.A)", img: backgrounds[2] },
  { text: "At home I am a nice guy: but I don't want the world to know. Humble people, I've found, don't get very far.", author: "Muhammad Ali", img: backgrounds[3] },
  { text: "May Allah bless the man who says less and does more.", author: "Umar ibn Al-Khattāb (R.A)", img: backgrounds[4] },
  { text: "My place is placeless, a trace of the traceless.", author: "Rumi", img: backgrounds[5] },
  { text: "Success Is Not Final, Failure Is Not Fatal: It Is The Courage To Continue That Counts.", author: "Winston Churchill", img: backgrounds[6] },
  { text: "Plants And Minerals Are Bound To Predestination. The Faithful Is Only Bound To The Divine Orders.", author: "Muhammad Iqbal", img: backgrounds[7] },
  { text: "As We Express Our Gratitude, We Must Never Forget That The Highest Appreciation Is Not To Utter Words, But To Live By Them.", author: "John F. Kennedy", img: backgrounds[0] },
  { text: "Death is the easiest of all things after it, and the hardest of all things before it.", author: "Abu Bakr (R.A)", img: backgrounds[1] },
  { text: "When In Doubt, Go For The Dick Joke.", author: "Robin Williams", img: backgrounds[2] },
  { text: "I Do Not Think Much Of A Man Who Is Not Wiser Today Than He Was Yesterday.", author: "Abraham Lincoln", img: backgrounds[3] },
  { text: "Don'T Be Distracted By Criticism. Remember ~ The Only Taste Of Success Some People Have Is When They Take A Bite Out Of You.", author: "Zig Ziglar", img: backgrounds[4] }
];

export const getDailyQuote = (): QuoteAsset => {
  const today = new Date();
  
  // Format MM-DD
  const month = (today.getMonth() + 1).toString().padStart(2, '0');
  const day = today.getDate().toString().padStart(2, '0');
  const dateKey = `${month}-${day}`;

  // 1. Check Special Dates
  if (specialDates[dateKey]) {
    return specialDates[dateKey];
  }

  // 2. Calculate Day of Year (1-366)
  const start = new Date(today.getFullYear(), 0, 0);
  const diff = today.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);

  // 3. Rotate through generic quotes (guaranteed to cover 365)
  const quoteIndex = (dayOfYear - 1) % genericQuotes.length;
  const selected = genericQuotes[quoteIndex];

  return {
    text: selected.text,
    author: selected.author,
    image: selected.img
  };
};
