import 'dotenv/config';
import Stripe from 'stripe';
import fs from 'fs';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

const PRICING_PLANS = [
    {
        id: 'starter',
        name: 'Luminel STARTER',
        description: 'Per il professionista indipendente - Elite Founder Offer',
        priceMonthly: 33,
        priceAnnual: 330,
    },
    {
        id: 'pro',
        name: 'Luminel PRO',
        description: 'Per il salone moderno che scala - Elite Founder Offer',
        priceMonthly: 55,
        priceAnnual: 550,
    },
    {
        id: 'signature',
        name: 'Luminel SIGNATURE',
        description: 'L\'esperienza definitiva per studi premium - Elite Founder Offer',
        priceMonthly: 88,
        priceAnnual: 880,
    },
    {
        id: 'empire',
        name: 'Luminel EMPIRE',
        description: 'Controllo totale per imperi multicentro - Elite Founder Offer',
        priceMonthly: 138,
        priceAnnual: 1380,
    }
];

async function setup() {
    console.log('🚀 Starting Luminel Stripe Setup...');
    const priceMapping = {};

    for (const plan of PRICING_PLANS) {
        console.log(`\n📦 Creating product: ${plan.name}...`);

        // 1. Create Product
        const product = await stripe.products.create({
            name: plan.name,
            description: plan.description,
            metadata: { planId: plan.id }
        });

        console.log(`✅ Product created: ${product.id}`);

        // 2. Create Monthly Price
        const monthlyPrice = await stripe.prices.create({
            unit_amount: plan.priceMonthly * 100, // cents
            currency: 'eur',
            recurring: { interval: 'month' },
            product: product.id,
            metadata: { planId: plan.id, cycle: 'monthly' }
        });
        console.log(`   - Monthly Price: ${monthlyPrice.id} (€${plan.priceMonthly})`);

        // 3. Create Annual Price
        const annualPrice = await stripe.prices.create({
            unit_amount: plan.priceAnnual * 100, // cents
            currency: 'eur',
            recurring: { interval: 'year' },
            product: product.id,
            metadata: { planId: plan.id, cycle: 'annual' }
        });
        console.log(`   - Annual Price: ${annualPrice.id} (€${plan.priceAnnual})`);

        // 4. Create Payment Links
        const monthlyLink = await stripe.paymentLinks.create({
            line_items: [{ price: monthlyPrice.id, quantity: 1 }],
            after_completion: { type: 'redirect', redirect: { url: `${process.env.VITE_SITE_URL || 'http://localhost:3000'}/#/success?session_id={CHECKOUT_SESSION_ID}` } },
            metadata: { planId: plan.id, cycle: 'monthly' }
        });

        const annualLink = await stripe.paymentLinks.create({
            line_items: [{ price: annualPrice.id, quantity: 1 }],
            after_completion: { type: 'redirect', redirect: { url: `${process.env.VITE_SITE_URL || 'http://localhost:3000'}/#/success?session_id={CHECKOUT_SESSION_ID}` } },
            metadata: { planId: plan.id, cycle: 'annual' }
        });

        priceMapping[plan.id] = {
            monthly: { priceId: monthlyPrice.id, url: monthlyLink.url },
            annual: { priceId: annualPrice.id, url: annualLink.url }
        };
    }

    console.log('\n--- STRIPE PRICE MAPPING ---');
    const result = JSON.stringify(priceMapping, null, 2);
    console.log(result);

    const tsContent = `// Auto-generated by setupStripe.js\nexport const STRIPE_PRICES = ${result} as const;\n\nexport type PlanId = keyof typeof STRIPE_PRICES;\nexport type BillingCycle = 'monthly' | 'annual';\n`;
    fs.writeFileSync('./services/stripePrices.ts', tsContent);

    console.log('\n✅ Price IDs successfully written to /services/stripePrices.ts');
    console.log('--- END ---');
}

setup().catch(err => {
    console.error('❌ Error setting up Stripe:', err);
    process.exit(1);
});
